<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Owner extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Owner_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'owner/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'owner/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'owner/index.html';
            $config['first_url'] = base_url() . 'owner/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Owner_model->total_rows($q);
        $owner = $this->Owner_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'owner_data' => $owner,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'judul_page' => 'Owner Toko',
            'konten' => 'owner/owner_list',
        );
        $this->load->view('v_index', $data);
    }

    public function read($id) 
    {
        $row = $this->Owner_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_owner' => $row->id_owner,
		'owner' => $row->owner,
	    );
            $this->load->view('owner/owner_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('owner'));
        }
    }

    public function create() 
    {
        $data = array(
            'judul_page' => 'Owner Toko',
            'konten' => 'owner/owner_form',
            'button' => 'Create',
            'action' => site_url('owner/create_action'),
	    'id_owner' => set_value('id_owner'),
	    'owner' => set_value('owner'),
	);
        $this->load->view('v_index', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'owner' => $this->input->post('owner',TRUE),
	    );

            $this->Owner_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('owner'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Owner_model->get_by_id($id);

        if ($row) {
            $data = array(
                'judul_page' => 'Owner Toko',
                'konten' => 'owner/owner_form',
                'button' => 'Update',
                'action' => site_url('owner/update_action'),
		'id_owner' => set_value('id_owner', $row->id_owner),
		'owner' => set_value('owner', $row->owner),
	    );
            $this->load->view('v_index', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('owner'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_owner', TRUE));
        } else {
            $data = array(
		'owner' => $this->input->post('owner',TRUE),
	    );

            $this->Owner_model->update($this->input->post('id_owner', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('owner'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Owner_model->get_by_id($id);

        if ($row) {
            $this->Owner_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('owner'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('owner'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('owner', 'owner', 'trim|required');

	$this->form_validation->set_rules('id_owner', 'id_owner', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Owner.php */
/* Location: ./application/controllers/Owner.php */
/* Please DO NOT modify this information : */
/* Generated by Boy Kurniawan 2019-11-21 00:13:07 */
/* https://jualkoding.com */